/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jamff_ffmpeg_VideoUtils */

#ifndef _Included_com_jamff_ffmpeg_VideoUtils
#define _Included_com_jamff_ffmpeg_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jamff_ffmpeg_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jamff_ffmpeg_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_jamff_ffmpeg_VideoUtils
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jamff_ffmpeg_VideoUtils_version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
