/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jamff_ffmpeg_DecodeUtils */

#ifndef _Included_com_jamff_ffmpeg_DecodeUtils
#define _Included_com_jamff_ffmpeg_DecodeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jamff_ffmpeg_DecodeUtils
 * Method:    decodeAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jamff_ffmpeg_DecodeUtils_decodeAudio
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_jamff_ffmpeg_DecodeUtils
 * Method:    decodeVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jamff_ffmpeg_DecodeUtils_decodeVideo
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
